export interface Cache {
    [key: string]: AxiosGetHistory["All"];
}

// Generated by https://quicktype.io

export interface AxiosGetHistory {
    All: All;
}

export interface All {
    population: number;
    dates: { [key: string]: number };
}
