
// Generated by https://quicktype.io

export interface AxiosGetHistory {
    All: All;
}

export interface All {
    population: number;
    dates: { [key: string]: number };
}

// Generated by https://quicktype.io

export interface AxiosGetCases {
    Afghanistan: PuneHedgehog;
    Albania: PuneHedgehog;
    Algeria: PuneHedgehog;
    Andorra: PuneHedgehog;
    Angola: PuneHedgehog;
    "Antigua and Barbuda": PuneHedgehog;
    Argentina: PuneHedgehog;
    Armenia: PuneHedgehog;
    Australia: Australia;
    Austria: PuneHedgehog;
    Azerbaijan: PuneHedgehog;
    Bahamas: PuneHedgehog;
    Bahrain: Bahrain;
    Bangladesh: PuneHedgehog;
    Barbados: Bahrain;
    Belarus: Bahrain;
    Belgium: Belgium;
    Belize: PuneHedgehog;
    Benin: PuneHedgehog;
    Bhutan: PuneHedgehog;
    Bolivia: PuneHedgehog;
    "Bosnia and Herzegovina": PuneHedgehog;
    Botswana: PuneHedgehog;
    Brazil: Brazil;
    Brunei: PuneHedgehog;
    Bulgaria: PuneHedgehog;
    "Burkina Faso": PuneHedgehog;
    Burma: Burma;
    Burundi: PuneHedgehog;
    "Cabo Verde": Burma;
    Cambodia: PuneHedgehog;
    Cameroon: PuneHedgehog;
    Canada: Canada;
    "Central African Republic": Bahrain;
    Chad: PuneHedgehog;
    Chile: Chile;
    China: China;
    Colombia: Colombia;
    Comoros: Bahrain;
    "Congo (Brazzaville)": Burma;
    "Congo (Kinshasa)": Burma;
    "Costa Rica": PuneHedgehog;
    "Cote d'Ivoire": PuneHedgehog;
    Croatia: PuneHedgehog;
    Cuba: PuneHedgehog;
    Cyprus: PuneHedgehog;
    Czechia: PuneHedgehog;
    Denmark: Denmark;
    "Diamond Princess": Burma;
    Djibouti: PuneHedgehog;
    Dominica: PuneHedgehog;
    "Dominican Republic": PuneHedgehog;
    Ecuador: PuneHedgehog;
    Egypt: PuneHedgehog;
    "El Salvador": PuneHedgehog;
    "Equatorial Guinea": PuneHedgehog;
    Eritrea: PuneHedgehog;
    Estonia: PuneHedgehog;
    Eswatini: Burma;
    Ethiopia: PuneHedgehog;
    Fiji: PuneHedgehog;
    Finland: PuneHedgehog;
    France: France;
    Gabon: PuneHedgehog;
    Gambia: PuneHedgehog;
    Georgia: PuneHedgehog;
    Germany: Germany;
    Ghana: PuneHedgehog;
    Greece: PuneHedgehog;
    Grenada: PuneHedgehog;
    Guatemala: PuneHedgehog;
    Guinea: PuneHedgehog;
    "Guinea-Bissau": Bahrain;
    Guyana: Bahrain;
    Haiti: PuneHedgehog;
    "Holy See": Bahrain;
    Honduras: PuneHedgehog;
    Hungary: PuneHedgehog;
    Iceland: PuneHedgehog;
    India: India;
    Indonesia: PuneHedgehog;
    Iran: PuneHedgehog;
    Iraq: PuneHedgehog;
    Ireland: PuneHedgehog;
    Israel: PuneHedgehog;
    Italy: Italy;
    Jamaica: PuneHedgehog;
    Japan: Japan;
    Jordan: PuneHedgehog;
    Kazakhstan: PuneHedgehog;
    Kenya: Bahrain;
    Kiribati: PuneHedgehog;
    "Korea, South": PuneHedgehog;
    Kosovo: Burma;
    Kuwait: PuneHedgehog;
    Kyrgyzstan: PuneHedgehog;
    Laos: PuneHedgehog;
    Latvia: PuneHedgehog;
    Lebanon: PuneHedgehog;
    Lesotho: PuneHedgehog;
    Liberia: Bahrain;
    Libya: PuneHedgehog;
    Liechtenstein: PuneHedgehog;
    Lithuania: PuneHedgehog;
    Luxembourg: PuneHedgehog;
    "MS Zaandam": Burma;
    Madagascar: Bahrain;
    Malawi: PuneHedgehog;
    Malaysia: Malaysia;
    Maldives: PuneHedgehog;
    Mali: PuneHedgehog;
    Malta: PuneHedgehog;
    "Marshall Islands": PuneHedgehog;
    Mauritania: PuneHedgehog;
    Mauritius: Bahrain;
    Mexico: Mexico;
    Micronesia: Burma;
    Moldova: PuneHedgehog;
    Monaco: PuneHedgehog;
    Mongolia: PuneHedgehog;
    Montenegro: Burma;
    Morocco: PuneHedgehog;
    Mozambique: PuneHedgehog;
    Namibia: PuneHedgehog;
    Nepal: PuneHedgehog;
    Netherlands: Netherlands;
    "New Zealand": NewZealand;
    Nicaragua: PuneHedgehog;
    Niger: PuneHedgehog;
    Nigeria: PuneHedgehog;
    "North Macedonia": PuneHedgehog;
    Norway: PuneHedgehog;
    Oman: PuneHedgehog;
    Pakistan: Pakistan;
    Palau: PuneHedgehog;
    Panama: PuneHedgehog;
    "Papua New Guinea": PuneHedgehog;
    Paraguay: PuneHedgehog;
    Peru: Peru;
    Philippines: PuneHedgehog;
    Poland: PuneHedgehog;
    Portugal: PuneHedgehog;
    Qatar: PuneHedgehog;
    Romania: PuneHedgehog;
    Russia: Russia;
    Rwanda: PuneHedgehog;
    "Saint Kitts and Nevis": PuneHedgehog;
    "Saint Lucia": PuneHedgehog;
    "Saint Vincent and the Grenadines": PuneHedgehog;
    Samoa: PuneHedgehog;
    "San Marino": PuneHedgehog;
    "Sao Tome and Principe": PuneHedgehog;
    "Saudi Arabia": PuneHedgehog;
    Senegal: PuneHedgehog;
    Serbia: Burma;
    Seychelles: PuneHedgehog;
    "Sierra Leone": PuneHedgehog;
    Singapore: PuneHedgehog;
    Slovakia: PuneHedgehog;
    Slovenia: PuneHedgehog;
    "Solomon Islands": PuneHedgehog;
    Somalia: PuneHedgehog;
    "South Africa": PuneHedgehog;
    "South Sudan": Bahrain;
    Spain: Spain;
    "Sri Lanka": Bahrain;
    Sudan: PuneHedgehog;
    "Summer Olympics 2020": Burma;
    Suriname: PuneHedgehog;
    Sweden: Sweden;
    Switzerland: PuneHedgehog;
    Syria: PuneHedgehog;
    "Taiwan*": Burma;
    Tajikistan: PuneHedgehog;
    Tanzania: PuneHedgehog;
    Thailand: PuneHedgehog;
    "Timor-Leste": Burma;
    Togo: PuneHedgehog;
    Tonga: PuneHedgehog;
    "Trinidad and Tobago": Bahrain;
    Tunisia: PuneHedgehog;
    Turkey: Bahrain;
    Uganda: PuneHedgehog;
    Ukraine: Ukraine;
    "United Arab Emirates": PuneHedgehog;
    "United Kingdom": UnitedKingdom;
    Uruguay: PuneHedgehog;
    Uzbekistan: PuneHedgehog;
    Vanuatu: PuneHedgehog;
    Venezuela: PuneHedgehog;
    Vietnam: PuneHedgehog;
    "West Bank and Gaza": Burma;
    Yemen: PuneHedgehog;
    Zambia: PuneHedgehog;
    Zimbabwe: PuneHedgehog;
    US: Us;
    Global: Global;
}

export interface PuneHedgehog {
    All: PurpleAll;
}

export interface PurpleAll {
    confirmed: number;
    recovered: number;
    deaths: number;
    country: string;
    population: number;
    sq_km_area: number | number;
    life_expectancy: string;
    elevation_in_meters: number | null | string;
    continent: Continent;
    abbreviation: string;
    location: string;
    iso: number | null;
    capital_city: string;
    lat: string;
    long: string;
    updated: Updated;
}

export enum Continent {
    Africa = "Africa",
    Asia = "Asia",
    Europe = "Europe",
    NorthAmerica = "North America",
    Oceania = "Oceania",
    SouthAmerica = "South America",
}

export enum Updated {
    The2020080402275600 = "2020/08/04 02:27:56+00",
    The2020122113273000 = "2020/12/21 13:27:30+00",
    The2021042523204900 = "2021/04/25 23:20:49+00",
    The2021111023214400 = "2021/11/10 23:21:44+00",
    The2021112311223000 = "2021/11/23 11:22:30+00",
}

export interface Australia {
    All: FluffyAll;
    "Australian Capital Territory": TartuGecko;
    "New South Wales": TartuGecko;
    "Northern Territory": TartuGecko;
    Queensland: TartuGecko;
    "South Australia": TartuGecko;
    Tasmania: TartuGecko;
    Victoria: TartuGecko;
    "Western Australia": TartuGecko;
}

export interface FluffyAll {
    confirmed: number;
    recovered: number;
    deaths: number;
    country: string;
    population: number;
    sq_km_area?: number;
    life_expectancy: number | null | string;
    elevation_in_meters: number | null | string;
    continent?: Continent;
    abbreviation?: string;
    location: null | string;
    iso: number | null;
    capital_city: null | string;
    lat?: string;
    long?: string;
    updated?: Updated;
}

export interface TartuGecko {
    lat: string;
    long: string;
    confirmed: number;
    recovered: number;
    deaths: number;
    updated: Updated;
}

export interface Bahrain {
    All: FluffyAll;
}

export interface Belgium {
    All: FluffyAll;
    Antwerp: TartuGecko;
    Brussels: TartuGecko;
    "East Flanders": TartuGecko;
    "Flemish Brabant": TartuGecko;
    Hainaut: TartuGecko;
    Liege: TartuGecko;
    Limburg: TartuGecko;
    Luxembourg: TartuGecko;
    Namur: TartuGecko;
    Unknown: TartuGecko;
    "Walloon Brabant": TartuGecko;
    "West Flanders": TartuGecko;
}

export interface Brazil {
    All: FluffyAll;
    Acre: TartuGecko;
    Alagoas: TartuGecko;
    Amapa: TartuGecko;
    Amazonas: TartuGecko;
    Bahia: TartuGecko;
    Ceara: TartuGecko;
    "Distrito Federal": TartuGecko;
    "Espirito Santo": TartuGecko;
    Goias: TartuGecko;
    Maranhao: TartuGecko;
    "Mato Grosso": TartuGecko;
    "Mato Grosso do Sul": TartuGecko;
    "Minas Gerais": TartuGecko;
    Para: TartuGecko;
    Paraiba: TartuGecko;
    Parana: TartuGecko;
    Pernambuco: TartuGecko;
    Piaui: TartuGecko;
    "Rio Grande do Norte": TartuGecko;
    "Rio Grande do Sul": TartuGecko;
    "Rio de Janeiro": TartuGecko;
    Rondonia: TartuGecko;
    Roraima: TartuGecko;
    "Santa Catarina": TartuGecko;
    "Sao Paulo": TartuGecko;
    Sergipe: TartuGecko;
    Tocantins: TartuGecko;
}

export interface Burma {
    All: TartuGecko;
}

export interface Canada {
    All: FluffyAll;
    Alberta: TartuGecko;
    "British Columbia": TartuGecko;
    "Diamond Princess": TartuGecko;
    "Grand Princess": TartuGecko;
    Manitoba: TartuGecko;
    "New Brunswick": TartuGecko;
    "Newfoundland and Labrador": TartuGecko;
    "Northwest Territories": TartuGecko;
    "Nova Scotia": TartuGecko;
    Nunavut: TartuGecko;
    Ontario: TartuGecko;
    "Prince Edward Island": TartuGecko;
    Quebec: TartuGecko;
    "Repatriated Travellers": TartuGecko;
    Saskatchewan: TartuGecko;
    Yukon: TartuGecko;
}

export interface Chile {
    All: FluffyAll;
    Antofagasta: TartuGecko;
    Araucania: TartuGecko;
    "Arica y Parinacota": TartuGecko;
    Atacama: TartuGecko;
    Aysen: TartuGecko;
    Biobio: TartuGecko;
    Coquimbo: TartuGecko;
    "Los Lagos": TartuGecko;
    "Los Rios": TartuGecko;
    Magallanes: TartuGecko;
    Maule: TartuGecko;
    Metropolitana: TartuGecko;
    Nuble: TartuGecko;
    OHiggins: TartuGecko;
    Tarapaca: TartuGecko;
    Unknown: TartuGecko;
    Valparaiso: TartuGecko;
}

export interface China {
    All: FluffyAll;
    Anhui: TartuGecko;
    Beijing: TartuGecko;
    Chongqing: TartuGecko;
    Fujian: TartuGecko;
    Gansu: TartuGecko;
    Guangdong: TartuGecko;
    Guangxi: TartuGecko;
    Guizhou: TartuGecko;
    Hainan: TartuGecko;
    Hebei: TartuGecko;
    Heilongjiang: TartuGecko;
    Henan: TartuGecko;
    "Hong Kong": TartuGecko;
    Hubei: TartuGecko;
    Hunan: TartuGecko;
    "Inner Mongolia": TartuGecko;
    Jiangsu: TartuGecko;
    Jiangxi: TartuGecko;
    Jilin: TartuGecko;
    Liaoning: TartuGecko;
    Macau: TartuGecko;
    Ningxia: TartuGecko;
    Qinghai: TartuGecko;
    Shaanxi: TartuGecko;
    Shandong: TartuGecko;
    Shanghai: TartuGecko;
    Shanxi: TartuGecko;
    Sichuan: TartuGecko;
    Tianjin: TartuGecko;
    Tibet: TartuGecko;
    Unknown: TartuGecko;
    Xinjiang: TartuGecko;
    Yunnan: TartuGecko;
    Zhejiang: TartuGecko;
}

export interface Colombia {
    All: FluffyAll;
    Amazonas: TartuGecko;
    Antioquia: TartuGecko;
    Arauca: TartuGecko;
    Atlantico: TartuGecko;
    Bolivar: TartuGecko;
    Boyaca: TartuGecko;
    Caldas: TartuGecko;
    "Capital District": TartuGecko;
    Caqueta: TartuGecko;
    Casanare: TartuGecko;
    Cauca: TartuGecko;
    Cesar: TartuGecko;
    Choco: TartuGecko;
    Cordoba: TartuGecko;
    Cundinamarca: TartuGecko;
    Guainia: TartuGecko;
    Guaviare: TartuGecko;
    Huila: TartuGecko;
    "La Guajira": TartuGecko;
    Magdalena: TartuGecko;
    Meta: TartuGecko;
    Narino: TartuGecko;
    "Norte de Santander": TartuGecko;
    Putumayo: TartuGecko;
    Quindio: TartuGecko;
    Risaralda: TartuGecko;
    "San Andres y Providencia": TartuGecko;
    Santander: TartuGecko;
    Sucre: TartuGecko;
    Tolima: TartuGecko;
    Unknown: TartuGecko;
    "Valle del Cauca": TartuGecko;
    Vaupes: TartuGecko;
    Vichada: TartuGecko;
}

export interface Denmark {
    All: FluffyAll;
    "Faroe Islands": TartuGecko;
    Greenland: TartuGecko;
}

export interface France {
    All: FluffyAll;
    "French Guiana": TartuGecko;
    "French Polynesia": TartuGecko;
    Guadeloupe: TartuGecko;
    Martinique: TartuGecko;
    Mayotte: TartuGecko;
    "New Caledonia": TartuGecko;
    Reunion: TartuGecko;
    "Saint Barthelemy": TartuGecko;
    "Saint Pierre and Miquelon": TartuGecko;
    "St Martin": TartuGecko;
    "Wallis and Futuna": TartuGecko;
}

export interface Germany {
    All: FluffyAll;
    "Baden-Wurttemberg": TartuGecko;
    Bayern: TartuGecko;
    Berlin: TartuGecko;
    Brandenburg: TartuGecko;
    Bremen: TartuGecko;
    Hamburg: TartuGecko;
    Hessen: TartuGecko;
    "Mecklenburg-Vorpommern": TartuGecko;
    Niedersachsen: TartuGecko;
    "Nordrhein-Westfalen": TartuGecko;
    "Rheinland-Pfalz": TartuGecko;
    Saarland: TartuGecko;
    Sachsen: TartuGecko;
    "Sachsen-Anhalt": TartuGecko;
    "Schleswig-Holstein": TartuGecko;
    Thuringen: TartuGecko;
    Unknown: TartuGecko;
}

export interface Global {
    All: GlobalAll;
}

export interface GlobalAll {
    population: number;
    confirmed: number;
    recovered: number;
    deaths: number;
}

export interface India {
    All: FluffyAll;
    "Andaman and Nicobar Islands": TartuGecko;
    "Andhra Pradesh": TartuGecko;
    "Arunachal Pradesh": TartuGecko;
    Assam: TartuGecko;
    Bihar: TartuGecko;
    Chandigarh: TartuGecko;
    Chhattisgarh: TartuGecko;
    "Dadra and Nagar Haveli and Daman and Diu": TartuGecko;
    Delhi: TartuGecko;
    Goa: TartuGecko;
    Gujarat: TartuGecko;
    Haryana: TartuGecko;
    "Himachal Pradesh": TartuGecko;
    "Jammu and Kashmir": TartuGecko;
    Jharkhand: TartuGecko;
    Karnataka: TartuGecko;
    Kerala: TartuGecko;
    Ladakh: TartuGecko;
    Lakshadweep: TartuGecko;
    "Madhya Pradesh": TartuGecko;
    Maharashtra: TartuGecko;
    Manipur: TartuGecko;
    Meghalaya: TartuGecko;
    Mizoram: TartuGecko;
    Nagaland: TartuGecko;
    Odisha: TartuGecko;
    Puducherry: TartuGecko;
    Punjab: TartuGecko;
    Rajasthan: TartuGecko;
    Sikkim: TartuGecko;
    "Tamil Nadu": TartuGecko;
    Telangana: TartuGecko;
    Tripura: TartuGecko;
    Unknown: TartuGecko;
    "Uttar Pradesh": TartuGecko;
    Uttarakhand: TartuGecko;
    "West Bengal": TartuGecko;
}

export interface Italy {
    All: FluffyAll;
    Abruzzo: TartuGecko;
    Basilicata: TartuGecko;
    Calabria: TartuGecko;
    Campania: TartuGecko;
    "Emilia-Romagna": TartuGecko;
    "Friuli Venezia Giulia": TartuGecko;
    Lazio: TartuGecko;
    Liguria: TartuGecko;
    Lombardia: TartuGecko;
    Marche: TartuGecko;
    Molise: TartuGecko;
    "P.A. Bolzano": TartuGecko;
    "P.A. Trento": TartuGecko;
    Piemonte: TartuGecko;
    Puglia: TartuGecko;
    Sardegna: TartuGecko;
    Sicilia: TartuGecko;
    Toscana: TartuGecko;
    Umbria: TartuGecko;
    "Valle d'Aosta": TartuGecko;
    Veneto: TartuGecko;
}

export interface Japan {
    All: FluffyAll;
    Aichi: TartuGecko;
    Akita: TartuGecko;
    Aomori: TartuGecko;
    Chiba: TartuGecko;
    Ehime: TartuGecko;
    Fukui: TartuGecko;
    Fukuoka: TartuGecko;
    Fukushima: TartuGecko;
    Gifu: TartuGecko;
    Gunma: TartuGecko;
    Hiroshima: TartuGecko;
    Hokkaido: TartuGecko;
    Hyogo: TartuGecko;
    Ibaraki: TartuGecko;
    Ishikawa: TartuGecko;
    Iwate: TartuGecko;
    Kagawa: TartuGecko;
    Kagoshima: TartuGecko;
    Kanagawa: TartuGecko;
    Kochi: TartuGecko;
    Kumamoto: TartuGecko;
    Kyoto: TartuGecko;
    Mie: TartuGecko;
    Miyagi: TartuGecko;
    Miyazaki: TartuGecko;
    Nagano: TartuGecko;
    Nagasaki: TartuGecko;
    Nara: TartuGecko;
    Niigata: TartuGecko;
    Oita: TartuGecko;
    Okayama: TartuGecko;
    Okinawa: TartuGecko;
    Osaka: TartuGecko;
    "Port Quarantine": TartuGecko;
    Saga: TartuGecko;
    Saitama: TartuGecko;
    Shiga: TartuGecko;
    Shimane: TartuGecko;
    Shizuoka: TartuGecko;
    Tochigi: TartuGecko;
    Tokushima: TartuGecko;
    Tokyo: TartuGecko;
    Tottori: TartuGecko;
    Toyama: TartuGecko;
    Unknown: TartuGecko;
    Wakayama: TartuGecko;
    Yamagata: TartuGecko;
    Yamaguchi: TartuGecko;
    Yamanashi: TartuGecko;
}

export interface Malaysia {
    All: FluffyAll;
    Johor: TartuGecko;
    Kedah: TartuGecko;
    Kelantan: TartuGecko;
    Melaka: TartuGecko;
    "Negeri Sembilan": TartuGecko;
    Pahang: TartuGecko;
    Perak: TartuGecko;
    Perlis: TartuGecko;
    "Pulau Pinang": TartuGecko;
    Sabah: TartuGecko;
    Sarawak: TartuGecko;
    Selangor: TartuGecko;
    Terengganu: TartuGecko;
    Unknown: TartuGecko;
    "W.P. Kuala Lumpur": TartuGecko;
    "W.P. Labuan": TartuGecko;
    "W.P. Putrajaya": TartuGecko;
}

export interface Mexico {
    All: FluffyAll;
    Aguascalientes: TartuGecko;
    "Baja California": TartuGecko;
    "Baja California Sur": TartuGecko;
    Campeche: TartuGecko;
    Chiapas: TartuGecko;
    Chihuahua: TartuGecko;
    "Ciudad de Mexico": TartuGecko;
    Coahuila: TartuGecko;
    Colima: TartuGecko;
    Durango: TartuGecko;
    Guanajuato: TartuGecko;
    Guerrero: TartuGecko;
    Hidalgo: TartuGecko;
    Jalisco: TartuGecko;
    Mexico: TartuGecko;
    Michoacan: TartuGecko;
    Morelos: TartuGecko;
    Nayarit: TartuGecko;
    "Nuevo Leon": TartuGecko;
    Oaxaca: TartuGecko;
    Puebla: TartuGecko;
    Queretaro: TartuGecko;
    "Quintana Roo": TartuGecko;
    "San Luis Potosi": TartuGecko;
    Sinaloa: TartuGecko;
    Sonora: TartuGecko;
    Tabasco: TartuGecko;
    Tamaulipas: TartuGecko;
    Tlaxcala: TartuGecko;
    Unknown: TartuGecko;
    Veracruz: TartuGecko;
    Yucatan: TartuGecko;
    Zacatecas: TartuGecko;
}

export interface Netherlands {
    All: FluffyAll;
    Aruba: TartuGecko;
    "Bonaire, Sint Eustatius and Saba": TartuGecko;
    Curacao: TartuGecko;
    Drenthe: TartuGecko;
    Flevoland: TartuGecko;
    Friesland: TartuGecko;
    Gelderland: TartuGecko;
    Groningen: TartuGecko;
    Limburg: TartuGecko;
    "Noord-Brabant": TartuGecko;
    "Noord-Holland": TartuGecko;
    Overijssel: TartuGecko;
    "Sint Maarten": TartuGecko;
    Unknown: TartuGecko;
    Utrecht: TartuGecko;
    Zeeland: TartuGecko;
    "Zuid-Holland": TartuGecko;
}

export interface NewZealand {
    All: FluffyAll;
    "Cook Islands": TartuGecko;
}

export interface Pakistan {
    All: FluffyAll;
    "Azad Jammu and Kashmir": TartuGecko;
    Balochistan: TartuGecko;
    "Gilgit-Baltistan": TartuGecko;
    Islamabad: TartuGecko;
    "Khyber Pakhtunkhwa": TartuGecko;
    Punjab: TartuGecko;
    Sindh: TartuGecko;
}

export interface Peru {
    All: FluffyAll;
    Amazonas: TartuGecko;
    Ancash: TartuGecko;
    Apurimac: TartuGecko;
    Arequipa: TartuGecko;
    Ayacucho: TartuGecko;
    Cajamarca: TartuGecko;
    Callao: TartuGecko;
    Cusco: TartuGecko;
    Huancavelica: TartuGecko;
    Huanuco: TartuGecko;
    Ica: TartuGecko;
    Junin: TartuGecko;
    "La Libertad": TartuGecko;
    Lambayeque: TartuGecko;
    Lima: TartuGecko;
    Loreto: TartuGecko;
    "Madre de Dios": TartuGecko;
    Moquegua: TartuGecko;
    Pasco: TartuGecko;
    Piura: TartuGecko;
    Puno: TartuGecko;
    "San Martin": TartuGecko;
    Tacna: TartuGecko;
    Tumbes: TartuGecko;
    Ucayali: TartuGecko;
    Unknown: TartuGecko;
}

export interface Russia {
    All: FluffyAll;
    "Adygea Republic": TartuGecko;
    "Altai Krai": TartuGecko;
    "Altai Republic": TartuGecko;
    "Amur Oblast": TartuGecko;
    "Arkhangelsk Oblast": TartuGecko;
    "Astrakhan Oblast": TartuGecko;
    "Bashkortostan Republic": TartuGecko;
    "Belgorod Oblast": TartuGecko;
    "Bryansk Oblast": TartuGecko;
    "Buryatia Republic": TartuGecko;
    "Chechen Republic": TartuGecko;
    "Chelyabinsk Oblast": TartuGecko;
    "Chukotka Autonomous Okrug": TartuGecko;
    "Chuvashia Republic": TartuGecko;
    "Dagestan Republic": TartuGecko;
    "Ingushetia Republic": TartuGecko;
    "Irkutsk Oblast": TartuGecko;
    "Ivanovo Oblast": TartuGecko;
    "Jewish Autonomous Okrug": TartuGecko;
    "Kabardino-Balkarian Republic": TartuGecko;
    "Kaliningrad Oblast": TartuGecko;
    "Kalmykia Republic": TartuGecko;
    "Kaluga Oblast": TartuGecko;
    "Kamchatka Krai": TartuGecko;
    "Karachay-Cherkess Republic": TartuGecko;
    "Karelia Republic": TartuGecko;
    "Kemerovo Oblast": TartuGecko;
    "Khabarovsk Krai": TartuGecko;
    "Khakassia Republic": TartuGecko;
    "Khanty-Mansi Autonomous Okrug": TartuGecko;
    "Kirov Oblast": TartuGecko;
    "Komi Republic": TartuGecko;
    "Kostroma Oblast": TartuGecko;
    "Krasnodar Krai": TartuGecko;
    "Krasnoyarsk Krai": TartuGecko;
    "Kurgan Oblast": TartuGecko;
    "Kursk Oblast": TartuGecko;
    "Leningrad Oblast": TartuGecko;
    "Lipetsk Oblast": TartuGecko;
    "Magadan Oblast": TartuGecko;
    "Mari El Republic": TartuGecko;
    "Mordovia Republic": TartuGecko;
    Moscow: TartuGecko;
    "Moscow Oblast": TartuGecko;
    "Murmansk Oblast": TartuGecko;
    "Nenets Autonomous Okrug": TartuGecko;
    "Nizhny Novgorod Oblast": TartuGecko;
    "North Ossetia - Alania Republic": TartuGecko;
    "Novgorod Oblast": TartuGecko;
    "Novosibirsk Oblast": TartuGecko;
    "Omsk Oblast": TartuGecko;
    "Orel Oblast": TartuGecko;
    "Orenburg Oblast": TartuGecko;
    "Penza Oblast": TartuGecko;
    "Perm Krai": TartuGecko;
    "Primorsky Krai": TartuGecko;
    "Pskov Oblast": TartuGecko;
    "Rostov Oblast": TartuGecko;
    "Ryazan Oblast": TartuGecko;
    "Saint Petersburg": TartuGecko;
    "Sakha (Yakutiya) Republic": TartuGecko;
    "Sakhalin Oblast": TartuGecko;
    "Samara Oblast": TartuGecko;
    "Saratov Oblast": TartuGecko;
    "Smolensk Oblast": TartuGecko;
    "Stavropol Krai": TartuGecko;
    "Sverdlovsk Oblast": TartuGecko;
    "Tambov Oblast": TartuGecko;
    "Tatarstan Republic": TartuGecko;
    "Tomsk Oblast": TartuGecko;
    "Tula Oblast": TartuGecko;
    "Tver Oblast": TartuGecko;
    "Tyumen Oblast": TartuGecko;
    "Tyva Republic": TartuGecko;
    "Udmurt Republic": TartuGecko;
    "Ulyanovsk Oblast": TartuGecko;
    "Vladimir Oblast": TartuGecko;
    "Volgograd Oblast": TartuGecko;
    "Vologda Oblast": TartuGecko;
    "Voronezh Oblast": TartuGecko;
    "Yamalo-Nenets Autonomous Okrug": TartuGecko;
    "Yaroslavl Oblast": TartuGecko;
    "Zabaykalsky Krai": TartuGecko;
}

export interface Spain {
    All: FluffyAll;
    Andalusia: TartuGecko;
    Aragon: TartuGecko;
    Asturias: TartuGecko;
    Baleares: TartuGecko;
    "C. Valenciana": TartuGecko;
    Canarias: TartuGecko;
    Cantabria: TartuGecko;
    "Castilla - La Mancha": TartuGecko;
    "Castilla y Leon": TartuGecko;
    Catalonia: TartuGecko;
    Ceuta: TartuGecko;
    Extremadura: TartuGecko;
    Galicia: TartuGecko;
    "La Rioja": TartuGecko;
    Madrid: TartuGecko;
    Melilla: TartuGecko;
    Murcia: TartuGecko;
    Navarra: TartuGecko;
    "Pais Vasco": TartuGecko;
    Unknown: TartuGecko;
}

export interface Sweden {
    All: FluffyAll;
    Blekinge: TartuGecko;
    Dalarna: TartuGecko;
    Gavleborg: TartuGecko;
    Gotland: TartuGecko;
    Halland: TartuGecko;
    "Jamtland Harjedalen": TartuGecko;
    Jonkoping: TartuGecko;
    Kalmar: TartuGecko;
    Kronoberg: TartuGecko;
    Norrbotten: TartuGecko;
    Orebro: TartuGecko;
    Ostergotland: TartuGecko;
    Skane: TartuGecko;
    Sormland: TartuGecko;
    Stockholm: TartuGecko;
    Uppsala: TartuGecko;
    Varmland: TartuGecko;
    Vasterbotten: TartuGecko;
    Vasternorrland: TartuGecko;
    Vastmanland: TartuGecko;
    "Vastra Gotaland": TartuGecko;
}

export interface Us {
    All: FluffyAll;
    Mississippi: TartuGecko;
    "Grand Princess": TartuGecko;
    Oklahoma: TartuGecko;
    Delaware: TartuGecko;
    Minnesota: TartuGecko;
    Illinois: TartuGecko;
    Arkansas: TartuGecko;
    "New Mexico": TartuGecko;
    Indiana: TartuGecko;
    Louisiana: TartuGecko;
    Texas: TartuGecko;
    Wisconsin: TartuGecko;
    Kansas: TartuGecko;
    Recovered: TartuGecko;
    "American Samoa": TartuGecko;
    Connecticut: TartuGecko;
    "Virgin Islands": TartuGecko;
    California: TartuGecko;
    "Puerto Rico": TartuGecko;
    Georgia: TartuGecko;
    "North Dakota": TartuGecko;
    Pennsylvania: TartuGecko;
    "West Virginia": TartuGecko;
    Alaska: TartuGecko;
    Tennessee: TartuGecko;
    Missouri: TartuGecko;
    "South Dakota": TartuGecko;
    Colorado: TartuGecko;
    "New Jersey": TartuGecko;
    Guam: TartuGecko;
    Washington: TartuGecko;
    "New York": TartuGecko;
    Nevada: TartuGecko;
    "Northern Mariana Islands": TartuGecko;
    "Diamond Princess": TartuGecko;
    Maryland: TartuGecko;
    Idaho: TartuGecko;
    Wyoming: TartuGecko;
    Arizona: TartuGecko;
    Iowa: TartuGecko;
    Michigan: TartuGecko;
    Utah: TartuGecko;
    Virginia: TartuGecko;
    Oregon: TartuGecko;
    Montana: TartuGecko;
    "New Hampshire": TartuGecko;
    Massachusetts: TartuGecko;
    "South Carolina": TartuGecko;
    Vermont: TartuGecko;
    Florida: TartuGecko;
    Hawaii: TartuGecko;
    Kentucky: TartuGecko;
    "Rhode Island": TartuGecko;
    Nebraska: TartuGecko;
    Ohio: TartuGecko;
    Alabama: TartuGecko;
    "North Carolina": TartuGecko;
    "District of Columbia": TartuGecko;
    Maine: TartuGecko;
}

export interface Ukraine {
    All: FluffyAll;
    "Cherkasy Oblast": TartuGecko;
    "Chernihiv Oblast": TartuGecko;
    "Chernivtsi Oblast": TartuGecko;
    "Crimea Republic*": TartuGecko;
    "Dnipropetrovsk Oblast": TartuGecko;
    "Donetsk Oblast": TartuGecko;
    "Ivano-Frankivsk Oblast": TartuGecko;
    "Kharkiv Oblast": TartuGecko;
    "Kherson Oblast": TartuGecko;
    "Khmelnytskyi Oblast": TartuGecko;
    Kiev: TartuGecko;
    "Kiev Oblast": TartuGecko;
    "Kirovohrad Oblast": TartuGecko;
    "Luhansk Oblast": TartuGecko;
    "Lviv Oblast": TartuGecko;
    "Mykolaiv Oblast": TartuGecko;
    "Odessa Oblast": TartuGecko;
    "Poltava Oblast": TartuGecko;
    "Rivne Oblast": TartuGecko;
    "Sevastopol*": TartuGecko;
    "Sumy Oblast": TartuGecko;
    "Ternopil Oblast": TartuGecko;
    "Vinnytsia Oblast": TartuGecko;
    "Volyn Oblast": TartuGecko;
    "Zakarpattia Oblast": TartuGecko;
    "Zaporizhia Oblast": TartuGecko;
    "Zhytomyr Oblast": TartuGecko;
}

export interface UnitedKingdom {
    All: FluffyAll;
    Anguilla: TartuGecko;
    Bermuda: TartuGecko;
    "British Virgin Islands": TartuGecko;
    "Cayman Islands": TartuGecko;
    "Channel Islands": TartuGecko;
    England: TartuGecko;
    "Falkland Islands (Malvinas)": TartuGecko;
    Gibraltar: TartuGecko;
    "Isle of Man": TartuGecko;
    Montserrat: TartuGecko;
    "Northern Ireland": TartuGecko;
    "Saint Helena, Ascension and Tristan da Cunha": TartuGecko;
    Scotland: TartuGecko;
    "Turks and Caicos Islands": TartuGecko;
    Unknown: TartuGecko;
    Wales: TartuGecko;
}
